<?php

namespace AppBundle\Entity;

/**
 * ComplejidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplejidadRepository extends \Doctrine\ORM\EntityRepository
{
}
