<?php

namespace AppBundle\Entity;

/**
 * EjercicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EjercicioRepository extends \Doctrine\ORM\EntityRepository
{
	public function privacityUpdate()
    {
    	$ejercicios = $this->getEntityManager()->createQuery(
                "SELECT e FROM AppBundle:Ejercicio e WHERE e.visibilidad = :visibilidad"
            )->setParameter('visibilidad', 'privado')->getResult();

    	$fecha2 = new \DateTime();
    	foreach ($ejercicios as $ejercicio) {
    		$fecha1 = $ejercicio->getFechaCreacion();
        	$interval = date_diff($fecha1, $fecha2);
            $num_days = $interval->format('%R%a');

            if( $num_days >= 15 ){
	            $entity = $this->getEntityManager()->createQuery(
                "UPDATE AppBundle:Ejercicio e SET e.visibilidad = 'publico' WHERE e.id = :id")->setParameter(
                'id', $ejercicio->getId())->getResult(); 
            }
    	}
    }
}
