<?php

namespace AppBundle\Entity;

/**
 * SubtemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubtemaRepository extends \Doctrine\ORM\EntityRepository
{
}
